name = "dand-session-do"
main = "src/index.ts"
compatibility_date = "2024-04-24"
usage_model = "unbound"

[durable_objects]
bindings = [
  { name = "SESSION_HUB", class_name = "SessionHub" }
]

[[migrations]]
tag = "v1"
new_classes = ["SessionHub"]

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true
